# Generated by Django 5.1 on 2024-08-18 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_pcpart_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transaction_id',
            field=models.UUIDField(default=123234345, editable=False, unique=True),
            preserve_default=False,
        ),
    ]
